apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: eg
  namespace: envoy-gateway-system
spec:
  extraArgs:
    - --use-dynamic-base-id
  # Must monitor this as it was added after the svc is already deployed
  telemetry:
    tracing:
      samplingRate: 100
      provider:
        host: otel-collector.observability.svc.cluster.local
        port: 4317
        type: OpenTelemetry
  provider:
    type: Kubernetes
    kubernetes:
      envoyDaemonSet:
        patch:
          type: StrategicMerge
          value:
            spec:
              template:
                metadata:
                  labels:
                    run: envoy-hostnet
                spec:
                  hostNetwork: true
                  dnsPolicy: ClusterFirstWithHostNet
                  securityContext:
                    runAsUser: 101
                  containers:
                    - name: envoy
                      securityContext:
                        capabilities:
                          add: ["NET_BIND_SERVICE"]
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: eg
    namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
  namespace: envoy-gateway-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: eg
  listeners:
    - name: prod-https
      hostname: "*.austinbayley.co.uk"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: prod-austinbayley-tls
            kind: Secret
            group: ""
    - name: stg-https
      hostname: "*.stg.austinbayley.co.uk"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: stg-austinbayley-tls
            kind: Secret
            group: ""
