apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: default-gateway-traffic-policy
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: default-gateway
  enableProxyProtocol: true
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 1
  headers:
    earlyRequestHeaders:
      set:
      - name: X-Real-IP
        value: "%REQ(X-ENVOY-EXTERNAL-ADDRESS)%"
      - name: X-Client-IP-CF
        value: "%REQ(CF-Connecting-IP)%"