apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  oci.server: |
    clustervcn.oraclevcn.com:53 {
        errors
        cache 30
        forward . 169.254.169.254
    }