apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: oidc-discovery-route
  namespace: default
spec:
  parentRefs:
    - name: default-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "kube.austinbayley.co.uk"
  rules:
    - matches:
        - path:
            type: Exact
            value: "/.well-known/openid-configuration"
      backendRefs:
        - name: kubernetes
          port: 443
    - matches:
        - path:
            type: Exact
            value: "/openid/v1/jwks"
      backendRefs:
        - name: kubernetes
          port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: api-server-tls
  namespace: default
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: kubernetes
  validation:
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: kube-root-ca.crt
    hostname: kubernetes.default.svc
