apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: oidc-discovery-route
  namespace: default
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: kube-system
  hostnames:
    - "kube.austinbayley.co.uk"
  rules:
    - matches:
        - path:
            type: Exact
            value: "/.well-known/openid-configuration"
      backendRefs:
        - name: oidc-nginx-proxy
          port: 80
    - matches:
        - path:
            type: Exact
            value: "/openid/v1/jwks"
      backendRefs:
        - name: oidc-nginx-proxy
          port: 80
