apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: temporal-server-tls
  namespace: temporal
spec:
  secretName: temporal-server-tls
  issuerRef:
    name: temporal-ca-issuer
    kind: Issuer
  commonName: temporal
  dnsNames:
    - temporal
    - temporal.svc
    - temporal.svc.cluster.local
  duration: 8760h
  privateKey:
    algorithm: RSA
    size: 2048
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: temporal-admin-client
  namespace: temporal
spec:
  secretName: temporal-admin-client
  duration: 8760h 
  renewBefore: 720h
  commonName: temporal-admin
  usages:
    - client auth
  issuerRef:
    name: temporal-ca-issuer
    kind: Issuer
