apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: temporal-route
  namespace: temporal
spec:
  parentRefs:
    - name: default-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "temporal.austinbayley.co.uk"
  rules:
    - backendRefs:
        - name: temporal-web
          port: 8080
