createNamespace: false

podDisruptionBudget:
  maxUnavailable: 1

hpa:
  enabled: true 
  minReplicas: 1
  maxReplicas: 2

config:
  envoyGateway:
    rateLimit:
      failClosed: false
      backend:
        type: Redis
        redis:
          url: "valkey.envoy-gateway-system.svc.cluster.local:6379"
    extensionApis:
      enableBackend: true