apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-repo
  namespace: argocd
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: oci-secret-store
    kind: ClusterSecretStore
  target:
    name: github-repo
    template:
      type: git
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: https://github.com/abayleypublic
        githubAppID: "1276323"
        githubAppInstallationID: "66865382"
        githubAppPrivateKey: "{{ .privateKey }}"
  data:
    - secretKey: privateKey
      remoteRef:
        key: argocd_github_repo_private_key
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abayleypublic/apps
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true
      include: '*application.yaml'
  destination:
    server: https://kube.austinbayley.co.uk:6443
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true