apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: oci-secret-store
    kind: ClusterSecretStore
  target:
    name: github-repo
    template:
      type: git
      data:
        url: https://github.com/abayleypublic
        githubAppID: "1276323"
        githubAppInstallationID: "66865382"
        githubAppPrivateKey: "{{ .privateKey }}"
  data:
    - secretKey: privateKey
      remoteRef:
        key: argocd_github_repo_private_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-client-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: oci-secret-store
    kind: ClusterSecretStore
  target:
    name: github-client-secret
  data:
    - secretKey: value
      remoteRef:
        key: argocd_github_client_secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portfolio-cluster-secret
  namespace: argocd
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: oci-secret-store
    kind: ClusterSecretStore
  target:
    name: portfolio-cluster-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
      data:
        name: kube
        server: https://kube.austinbayley.co.uk:6443
        config: |
          {
            "tlsClientConfig": {
              "insecure": false,
              "caData": "{{ .caData }}",
              "certData": "{{ .certData }}",
              "keyData": "{{ .keyData }}"
            }
          }
  data:
    - secretKey: caData
      remoteRef:
        key: k3s_ca_certificate
    - secretKey: certData
      remoteRef:
        key: k3s_client_certificate
    - secretKey: keyData
      remoteRef:
        key: k3s_client_key
