apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lb-pool"
  namespace: kube-system
spec:
  blocks:
    - cidr: "10.0.64.0/18"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: kube-system
spec:
  addresses:
    - type: IPAddress
      value: "10.0.64.50"
  gatewayClassName: cilium
  listeners:
    - name: https
      hostname: "*.austinbayley.co.uk"
      port: 443
      protocol: TLS
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All
